### PR TITLE
Issue #17

### PR DESCRIPTION
**Pull request by nandofromthebando**
translating .sh files into corresponding .ps1 files

### CODE REVIEW

**Review by Jarvis-Yu — APPROVED** [review]
LGTM, thanks for your help

**Comment by nandofromthebando** [comment]
Thank you I'll see if there is other issues that I can work on too!

**Comment by Jarvis-Yu** [comment]
Thanks for your help too.

If you do want to work "into" the project, I suggest you to pick up the Calx's Art (Issue #4) one, completing it should give you some sort of overview of the project.

If you just want to give some general help, please let me know, I'll try to think of some that is not picked up yet.

**Comment by nandofromthebando** [comment]
Ok cool thank you I'll check it out!

**Pull request merged**
