### PR TITLE
First part of issue #4

### PR DESCRIPTION
**Pull request by nandofromthebando**
Hello I wanted to send the first part of the issue #4, before I go ahead and implement the test_card.py. Please let me know if this looks correct and if there is anything that I need to add or change!

### CODE REVIEW

**Comment by Jarvis-Yu** [comment]
I'm glad that you do want to work into the project, but your changes seems a bit off. Do you have discord? You may find the discord server link in the [wiki page](https://github.com/Jarvis-Yu/Dottore-Genius-Invokation-TCG-Simulator/wiki). Please don't hesitate to join and probably ask me some questions regarding the code base.

(In this PR, you modified the template for all cards, which is apparently not something desirable, so I'll reject this one. Sorry)

**Comment by Jarvis-Yu** [comment]
I'm writing documentations for this project (in progress), might be of some help.

**Comment by Jarvis-Yu** [comment]
btw, regarding this specific issue #4, I recommend you to observe how other cards are implemented, especially StarSigns.

**Comment by nandofromthebando** [comment]
ok sorry it wasn't what you were looking for thank ill check out how those other cards are implemented!

**Comment by nandofromthebando** [comment]
Thank you for writing down documentation as well much appreciated!

**Pull request closed without merging**
